name: Repo dispatch

# Trigger the workflow on push to
# - Neurolang or
# - neurolang-ipywidgets
# projects. 
on:
  push:
    branches:
      - master
      - test
  repository_dispatch:
    types: [ NeuroLang, neurolang-ipywidgets]

jobs:
  test_notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.CI_TRIGGER_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
          python -m venv test_env
          . test_env/bin/activate
          python -m pip install --upgrade pip
          pip install .
      - name: Run notebook tests
        run: |
          echo "Running tests due to push in ${{ github.event.action }}"
          . test_env/bin/activate
          jupytext notebooks/simple_voila_ui.py --set-kernel - --execute
#          for file in ./notebooks/*.py; do jupytext "$file" --set-kernel - --execute; done
